package Threads;

public class ResultTask extends Thread {
    public void run() {
        System.out.println("Result generated by : "+Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();  // Normal Execution -> always the main Thread
        t1.start(); // Multi Threading -> new Thread is Created
        // ℹ️ start() internally calls run()
        // ✅ Thread cannot be started twice
    }
}